### PR TITLE
feat: ignore existing trace

### PR DESCRIPTION
**Pull request by greut**
Using Kong as our API Gateway, we'd like to prevent external actor to pollute the traces. It's currently done using the request-transformer plugin (https://github.com/Kong/kong-plugin-request-transformer/pull/32) but implies lowering the PRIORITY of this zipkin.

By setting `header_type` to `ignore`, it won't read any tracing headers from the incoming request and start a new one using the `default_header_type` value (or falling back to `b3`)

### CODE REVIEW

**Review by kikito — CHANGES_REQUESTED** [review]
Hello @greut , thank you for this PR.

Do you think you could add some tests for it? See how other options are tested in the `spec/` folder.

**Comment by greut** [comment]
> Do you think you could add some tests for it? See how other options are tested in the `spec/` folder.

the handler is not tested so far; I can take a look into it but it requires some work.

**Comment by jcchavezs** [comment]
Not sure about this change, I would implement this as a request sampler
instead which is an abstraction that always unsample traces
https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Instrumentation/Http/Server/HttpServerTracing.php#L49.
This opens he possibility to a broader abstraction for different sampling
strategies based on the request.

Current implementation looks like mixing different concepts.

José Carlos Chávez


tir. 9. feb. 2021 kl. 18:54 skrev Yoan Blanc <notifications@github.com>:

**Comment by greut** [comment]
> which is an abstraction that always unsample traces

@jcchavezs Thanks, however I dont' quite understand how it works from the link you've provided. The goal is not to act on the sampling strategy but on the trace capture one. Kong being exposed to the internet, we don't want it to accept incoming traces.

https://www.w3.org/TR/trace-context/#denial-of-service

**Comment by kikito** [comment]
Thanks for this PR. I merged it with small modifications (including a test) in #125

> I would implement this as a request sampler

That could be an option at the Zipkin level, but not at the Kong plugin level - that would require us to include source code as part of the plugin configuration, which is something we are not prepared to support for now. There are considerations about security and permissions to be had, and that would drag this discussion for even longer. For now, the presented feature is good enough.

**Pull request closed without merging**
