### PR TITLE
Convert opentracing tags to zipkin tags.

### PR DESCRIPTION
**Pull request by bnlong4417**
This fixes #13.

### CODE REVIEW

**Comment by james-callahan** [comment]
Merged :)

Btw, you don't have to create a new PR every time you change a commit: just force push to your branch and github will update the PR.

**Comment by bnlong4417** [comment]
:D, My first PR. But sorry, this PR fixes #8, not #13. Please reopen #13.

**Comment by james-callahan** [comment]
> :D, My first PR

Congrats!

Btw, you might want to complete https://docs.google.com/forms/d/e/1FAIpQLSfacQHac-PYIDIrDOi_W2l7cWxBDRIVBs6xE5HnlojPvdhL9g/viewform :)

**Comment by bnlong4417** [comment]
I submitted.

**Pull request merged**
