### PR TITLE
feat(*) w3c trace context with expanded tracing header control

### PR DESCRIPTION
**Pull request by kikito**
This is an expansion over #69 . In addition of recognizing the W3C header tracing header, this PR adds a new option called `header_type`, with 4 possible values:

* `preserve`: the plugin produces whatever format it receives on each request
* `b3-single`: always use b3 single
* `b3`: always use the "regular zipkin" headers, such as x-b3-traceid
* `w3c`: use the w3c format

When options.header_type is set to anything other than preserve, and the trace headers don't match (for example the config is b3-single but we receive a w3c-trace-context) then we should send both kinds of headers. A warning is logged.

### CODE REVIEW

**Comment by dalv666** [comment]
@kikito , do I understand correctly that this change will not support the header "uber-trace-id"? Is it possible to put in the configuration the name of the header, which will be responsible for the name of the trace header.

**Comment by kikito** [comment]
> do I understand correctly that this change will not support the header "uber-trace-id"

Your understanding is correct: this change does not include that header.

> Is it possible to put in the configuration the name of the header, which will be responsible for the name of the trace header.

That is not possible with this change.

**Comment by hbagdi** [comment]
@victorNewRelic Please fill in the contributor form to claim your Kong swag: https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt

**Comment by victorNewRelic** [comment]
Thanks, @hbagdi! Done!

**Pull request merged**
